// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * BackgroundVideoURLs returns the background video's sources, in preferred
 * order, served over a real loopback HTTP URL rather than the wails://
 * custom scheme (see videoserver.go for why).
 * @returns {$CancellablePromise<string[]>}
 */
export function BackgroundVideoURLs() {
    return $Call.ByID(1521833970).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function LatestModVersion() {
    return $Call.ByID(4255994990);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function OpenInstallDir() {
    return $Call.ByID(3907528091);
}

/**
 * @param {boolean} vanilla
 * @returns {$CancellablePromise<void>}
 */
export function Play(vanilla) {
    return $Call.ByID(4166957835, vanilla);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
