// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackgroundVideoURLs() {
  return window['go']['main']['App']['BackgroundVideoURLs']();
}

export function LatestModVersion() {
  return window['go']['main']['App']['LatestModVersion']();
}

export function OpenInstallDir() {
  return window['go']['main']['App']['OpenInstallDir']();
}

export function Play(arg1) {
  return window['go']['main']['App']['Play'](arg1);
}
