// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackgroundVideoURLs():Promise<Array<string>>;

export function LatestModVersion():Promise<string>;

export function OpenInstallDir():Promise<void>;

export function Play(arg1:boolean):Promise<void>;
